// Frozen pre-migration API: changes must remain assignable in both directions.
import type * as Old from './legacy/index.js';
import type * as New from 'wakachi';
declare let oldValues: typeof Old;
declare let newValues: typeof New;
oldValues = newValues;
newValues = oldValues;
declare let old0: Old.PosCategory;
declare let new0: New.PosCategory;
old0 = new0;
new0 = old0;
declare let old1: Old.PosTag;
declare let new1: New.PosTag;
old1 = new1;
new1 = old1;
declare let old2: Old.Morpheme;
declare let new2: New.Morpheme;
old2 = new2;
new2 = old2;
declare let old3: Old.AnalyzerOptions;
declare let new3: New.AnalyzerOptions;
old3 = new3;
new3 = old3;
declare let old4: Old.AnalyzerStatus;
declare let new4: New.AnalyzerStatus;
old4 = new4;
new4 = old4;
declare let old5: Old.LoadProgress;
declare let new5: New.LoadProgress;
old5 = new5;
new5 = old5;
declare let old6: Old.LoadTiming;
declare let new6: New.LoadTiming;
old6 = new6;
new6 = old6;
declare let old7: Old.FilesInfo;
declare let new7: New.FilesInfo;
old7 = new7;
new7 = old7;
declare let old8: Old.LoadResult;
declare let new8: New.LoadResult;
old8 = new8;
new8 = old8;
declare let old9: Old.CallOptions;
declare let new9: New.CallOptions;
old9 = new9;
new9 = old9;
declare let old10: Old.Analyzer;
declare let new10: New.Analyzer;
old10 = new10;
new10 = old10;
declare let old11: Old.AnalyzerErrorCode;
declare let new11: New.AnalyzerErrorCode;
old11 = new11;
new11 = old11;
declare let old12: Old.AnalyzerError;
declare let new12: New.AnalyzerError;
old12 = new12;
new12 = old12;
declare let old13: Old.RubySegment;
declare let new13: New.RubySegment;
old13 = new13;
new13 = old13;
declare let old14: Old.Bunsetsu;
declare let new14: New.Bunsetsu;
old14 = new14;
new14 = old14;
